---
- name: Create a directory if it does not exist
  file:
    path: /home/deck/Downloads/homebrew
    state: directory
    mode: '0755'

- name: Download Homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /home/deck/Downloads/homebrew

- name: Install Homebrew
  shell: /usr/bin/bash /home/deck/Downloads/homebrew/install.sh
  # Run the install script in non-interactive mode
  environment:
    NONINTERACTIVE: 1 

- name: Recursively remove download directory
  ansible.builtin.file:
    path: /home/deck/Downloads/homebrew
    state: absent
  